### ISSUE TITLE
pare:cer template for Spanish conjugations giving incorrect results

### ISSUE THREAD

**Issue by BrianSladek** [bretttolbert/verbecc#6]
Parecer, amanecer, anochecer, etc. all use the pare:cer template and give many incorrect results. For most tenses, only the él form is correct -- the rest are incorrect.

For instance, compare the results here: http://verbe.cc/vcfr/conjugate/es/parecer
With: https://www.spanishdict.com/conjugate/parecer

Cool library by the way!

**Comment by bretttolbert** [comment]
Sorry for the slow response. Thank you for bringing this to my attention. I've fixed the issues with these verbs in version 1.7.1.
